add task1 task2 task3 hw5
zhvkgj/SPbU pull request #12
Opened 2018-03-22 21:37 UTC by zhvkgj

2018-03-31 15:26 UTC, yurii-litvinov requested changes

2018-03-31 15:26 UTC, yurii-litvinov commented on course2/sem4/hw5/task1task2/task1task2/Program.fs
> +                        | _ when head = '(' || head = '{' || head = '[' -> checking tail (head::acc)
Можно же было `| '(' | '{' | '['`

2018-03-31 15:26 UTC, yurii-litvinov commented on course2/sem4/hw5/task1task2/task1task2/Program.fs
> +                                               else false
Копипаст суть ересь. F# хорош тем, что тут можно писать короткие вложенные функции, которые могут принимать значения из замыкания

2018-03-31 15:26 UTC, yurii-litvinov commented on course2/sem4/hw5/task1task2/task1task2/Program.fs
> +                else false
Ужасно :)

2018-03-31 15:26 UTC, yurii-litvinov commented on course2/sem4/hw5/task1task2/task1task2.Tests/UnitTests.fs
> +    listMulUltraPointFreeStyle5 5 [1; 2; 3] |> should equal [10; 20; 30]
В условии хотелось проверку FsCheck-ом

2018-03-31 15:26 UTC, yurii-litvinov commented on course2/sem4/hw5/task3/task3/Program.fs
> +   let dataToStrArr ls =
ToStrArr звучит как-то по-пиратски. ToStringArray было бы лучше

2018-03-31 15:26 UTC, yurii-litvinov commented on course2/sem4/hw5/task3/task3.tests/UnitTests.fs
> +    readFromFile "D:\Admin\Desktop\SPbU\course2\sem4\hw5\task3\phone_book.txt"
Потому что бекслеши --- это escape-символы. Попробуйте @"D:\Admin\Desktop\SPbU\course2\sem4\hw5\task3\phone_book.txt".

2018-03-31 15:26 UTC, yurii-litvinov commented on course2/sem4/hw5/task3/task3.tests/UnitTests.fs
> +    |> should equal [("Anna", "2194881498"); ("Elena", "0319393"); ("Samuel", "3213213477"); ("Rufus", "399100")]*)
Ещё неплохо бы сделать отдельные функции поиска и протестировать их. В обработчиках событий пользовательского интерфейса вообще не должно быть сложной логики

2018-03-31 21:35 UTC, zhvkgj commented on course2/sem4/hw5/task1task2/task1task2/Program.fs
> +                else false
Да.

2018-04-03 07:45 UTC, yurii-litvinov approved these changes
Хорошо, зачтены все три

2018-04-03 07:45 UTC, yurii-litvinov commented on course2/sem4/hw5/task3/task3.tests/UnitTests.fs
> +    readFromFile @"D:\Admin\Desktop\SPbU\course2\sem4\hw5\task3\phone_book.txt"
У меня такого нету :) Тестовые данные надо добавлять в проект и в свойствах файла в проекте ставить "копировать при сборке", после чего можно будет ссылаться на них по относительному пути

2018-04-03 08:38 UTC, merged